import { expect, test } from "@playwright/test";
import { PrismaClient } from "@prisma/client";

const target = new URL(process.env.DATABASE_URL ?? "http://invalid");
if (!["127.0.0.1", "localhost"].includes(target.hostname) || !target.pathname.includes("ani_reminder_qa")) throw new Error("Browser fixtures require the isolated QA database");
const db = new PrismaClient();
test.afterAll(async () => db.$disconnect());

test("weekly agenda completed library settings and search work together", async ({ page }, info) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const user = await db.user.findUniqueOrThrow({ where: { email: "qa@anireminder.example" } });
  await db.animeReminder.updateMany({ where: { userId: user.id, anilistId: 21 }, data: { enabled: true } });
  await page.goto("/login");
  await page.getByLabel("Email address", { exact: true }).fill(user.email);
  await page.getByLabel("Password", { exact: true }).fill("AniReminder-QA-2026");
  await page.locator('button[type="submit"]').click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await expect(page.getByRole("heading", { name: "Your week, on cue." })).toBeVisible();
  await expect(page.locator("main")).toContainText("One Piece");
  await page.screenshot({ path: `/tmp/ani-${info.project.name}-week.png`, fullPage: true });
  await page.goto("/dashboard?view=completed");
  await expect(page.locator("main")).toContainText("Frieren");
  await expect(page.locator("main")).not.toContainText("AIRING NOW");
  await page.goto("/dashboard?view=lineup");
  await page.getByRole("button", { name: "Awaiting schedule", exact: true }).click();
  await expect(page.locator(".lineup-list")).toContainText("Solo Leveling");
  await expect(page.locator(".lineup-list")).not.toContainText("One Piece");
  await page.getByRole("button", { name: "All shows", exact: true }).click();
  await page.getByRole("button", { name: "Add anime", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toBeVisible();
  await expect(page.getByRole("searchbox", { name: "Search anime titles" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole("button", { name: "Add anime", exact: true })).toBeFocused();
  await page.goto("/dashboard?view=settings");
  await expect(page.getByRole("heading", { name: "Your alerts", exact: true })).toBeVisible();
  const checkbox = page.getByRole("checkbox").first();
  await checkbox.uncheck();
  await page.getByRole("button", { name: "Save preferences", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("saved");
  await page.reload();
  await expect(checkbox).not.toBeChecked();
  await checkbox.check();
  await page.getByRole("button", { name: "Save preferences", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("saved");
  await page.goto("/dashboard?view=activity");
  await expect(page.locator("main")).toBeVisible();
  await page.screenshot({ path: `/tmp/ani-${info.project.name}-activity.png`, fullPage: true });
  const dimensions = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }));
  expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.width);
  expect(errors).toEqual([]);
});
