import Link from "next/link";
import Image from "next/image";
import { ArrowDown, ArrowRight, ArrowUpRight, BellRing, Check, Pause } from "lucide-react";
import { Brand } from "@/components/ui";

export function PublicHome({ isAuthenticated }: { isAuthenticated: boolean }) {
  const destination = isAuthenticated ? "/dashboard" : "/signup";
  return <main className="public-home" id="main-content">
    <a href="#how-it-works" className="skip-link">Skip to how it works</a>
    <header className="public-header"><Brand /><nav aria-label="Main navigation"><a href="#how-it-works" className="public-nav-about">How it works</a>{!isAuthenticated && <Link href="/login">Sign in</Link>}<Link href={destination} className="button button-secondary">{isAuthenticated ? "Open your lineup" : "Start your lineup"}<ArrowUpRight size={15} /></Link></nav></header>
    <section className="public-hero"><div className="public-hero-copy"><p className="eyebrow"><span className="hero-signal" />For whatever you’re watching next.</p><h1 className="title-font">THE WAIT.<br />HAS A <span>PLACE.</span></h1><p className="public-hero-description">Your anime. Their next episode. One clear lineup.<br className="desktop-break" /> Follow real release dates and get an ntfy nudge when it’s time.</p><div className="public-hero-actions"><Link href={destination} className="button button-primary">{isAuthenticated ? "Back to your lineup" : "Build my lineup"}<ArrowRight size={18} /></Link><a href="#how-it-works" className="public-how-link">Take a look <ArrowDown size={15} /></a></div><p className="public-hero-sources">Schedules by AniList <span>/</span> Alerts through ntfy</p></div>
      <div className="public-hero-stage"><div className="public-hero-art"><Image src="https://cdn.myanimelist.net/images/anime/1015/138006l.jpg" alt="" fill priority sizes="(max-width: 750px) 100vw, 46vw" /><div className="public-art-shade" /><p className="hero-art-caption">A LITTLE<br /><span>ANTICIPATION.</span></p></div><div className="example-lineup"><div className="example-header"><span>A look at your lineup</span><span>Illustrative example</span></div><div className="example-release"><span className="example-day">SUN<small>18:30</small></span><div><strong>Your Sunday show</strong><p>Episode 12 · Published airing</p></div><BellRing size={18} /></div><div className="example-release"><span className="example-state"><Pause size={18} /></span><div><strong>The next season</strong><p>Waiting for a published schedule</p></div><span className="example-quiet">Quiet</span></div><div className="example-release"><span className="example-state"><Check size={18} /></span><div><strong>A finished favorite</strong><p>Season complete · Alerts stopped</p></div><span className="example-quiet">Done</span></div></div></div>
    </section>
    <section className="public-principle"><div className="public-principle-heading"><p className="eyebrow">The calendar should earn your trust.</p><h2 className="title-font">REAL DATES.<br /><span>REAL QUIET.</span></h2><p>Between episodes, there’s enough to keep up with. Your reminder app should know when to speak up—and when the season is over.</p></div><div className="public-principle-list"><article><span className="status-badge status-scheduled">When it’s scheduled</span><h3>The next episode, at a glance.</h3><p>A seven-day timeline brings your published airings together, with clear episode numbers and times in IST.</p></article><article><span className="status-badge status-waiting">When it takes a break</span><h3>A pause in the schedule is a pause.</h3><p>Follow upcoming shows and hiatuses. If the next airing hasn’t been announced, your lineup waits for a real date.</p></article><article><span className="status-badge status-completed">When the credits roll</span><h3>Finished means finished.</h3><p>Completed seasons move out of the way. There are no made-up episodes and no weekly alerts that keep going.</p></article></div></section>
    <section id="how-it-works" className="public-setup"><div className="public-section-title"><h2 className="title-font">A GOOD LINEUP.<br />A SIMPLE SETUP.</h2><p>Three small steps.<br />Then back to the watching.</p></div><ol className="setup-steps"><li><span className="setup-number">01</span><div><h3>Find your shows.</h3><p>Search AniList and add the anime you’re following. Scheduled, upcoming, or on a break—there’s room for all of them.</p></div></li><li><span className="setup-number">02</span><div><h3>Connect your ntfy app.</h3><p>Choose a hard-to-guess topic, subscribe to it in ntfy, and send a test from Settings to check the connection.</p><a href="https://ntfy.sh/docs/subscribe/phone/" target="_blank" rel="noreferrer">Get the ntfy setup guide <ArrowUpRight size={14} /></a></div></li><li><span className="setup-number">03</span><div><h3>Keep the alerts you want.</h3><p>Choose a morning reminder, an airtime alert, or both. Pause individual shows whenever you need a break.</p></div></li></ol></section>
    <section className="public-close"><div><p>Your seat is saved.</p><h2 className="title-font">SEE YOU NEXT EPISODE.</h2></div><Link href={destination} className="button">{isAuthenticated ? "Open your lineup" : "Create your account"}<ArrowRight size={19} /></Link></section>
    <footer className="public-footer"><Brand /><p>Published airing times, not streaming availability.<br />Built for the shows you look forward to.</p><a href="#main-content">Back to top ↑</a></footer>
  </main>;
}
